### ISSUE TITLE
Re: Crash Opening Shops

### ISSUE THREAD

**Issue by RyanSalad** [glisco03/numismatic-overhaul#113]
Minecraft 1.19.2
Fabric 0.15.0
Numismatic Overhaul 0.2.9
owo-lib 0.9.3
I had decided to bite the bullet and not use Charm, but it started crashing again. I hadn't changed anything, and the only mods left are **Fabric API**, **owo-lib**, and **Numismatic Overhaul**
[crash-2023-11-30_05.54.18-server.txt](https://github.com/wisp-forest/numismatic-overhaul/files/13512393/crash-2023-11-30_05.54.18-server.txt)

It is not my intention to nag, but the fix that was told to me previously does not work, and this issue _should_ get resolved by someone eventually considering it has to be an owo-lib or Numismatic Overhaul issue by process of elimination.
_Originally posted by me in https://github.com/wisp-forest/numismatic-overhaul/issues/112#issuecomment-1833595420_

**Comment by gliscowo** [comment]
Thanks for reporting this problem! 

As it turns out, this has been a long-standing bug in the Shop's code that never manifested due to a related bug in Fabric Loader itself - which is why it occured when you updated to 0.15.0. I've now gone an published [an update](https://modrinth.com/mod/numismatic-overhaul/version/0.2.11+1.20.2) which fixes that problem on latest

For your case specifically, I'd recommend simply downgrading Fabric Loader - for now this should not cause problems. I'll see about getting a release with the fix out for 1.19.2 as well in the coming days

Cheers

**Comment by gliscowo** [comment]
Alright, a build for 1.19.2 has been released as [0.2.10 for 1.19](https://modrinth.com/mod/ZXm8hVxN/version/AsqQMuzE)
Cheers
