### ISSUE TITLE
Money Being Deleted When Trading

### ISSUE THREAD

**Issue by DarianLStephens** [glisco03/numismatic-overhaul#12]
When trading multiple items to a villager, if you click the output slot (coins) multiple times, any subsequent stacks will be deleted instead of stacking on the mouse.

**Comment by DarianLStephens** [comment]
Wow, that was a quick turnaround. Nice to see this fixed!
I guess people mostly shift-clicked or something while testing?

**Comment by gliscowo** [comment]
I would assume so, yeah. It's probably also just related to the fact this was caused by the behavior that allows you to merge coins into money bags in your inventory, which I added after the two major playtesting sessions
Well anyways, if you haven't seen it already a new build should be up on both curse and modrinth
Cheers

**Comment by DarianLStephens** [comment]
I saw the update on the Fabric server first. I thought I might wake up to a reply in the morning, but I guess this is a pretty big issue.
