### ISSUE TITLE
[Server Crash] Block Entities size mismatch - Fabric 1.19.2 - Urn

### ISSUE THREAD

**Issue by xR4YM0ND** [glisco03/numismatic-overhaul#44]
https://github.com/MehVahdJukaar/Supplementaries/issues/357

**Comment by xR4YM0ND** [comment]
No Crash Report got created ..

**Comment by xR4YM0ND** [comment]
I only have these 2 logs ( or one big log ) 

but i got disconnected and the server restaret

**Comment by xR4YM0ND** [comment]
i would love to try the dev version

Where can i download it, or is it to early

**Comment by Noaaan** [comment]
The error from Numismatic does not cause a crash, it is mostly a warning that the shop is being used weirdly. We are not able to provide any support for you in this case, since there simply is nothing to go on. 
The next version of Numismatic is not release ready yet, as we are still working on some missing features.

**Comment by xR4YM0ND** [comment]
alright <3
