### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by masmasmas66** [glisco03/numismatic-overhaul#45]
[crash-2022-09-10_15.53.20-client.txt](https://github.com/wisp-forest/numismatic-overhaul/files/9541218/crash-2022-09-10_15.53.20-client.txt)

From nowhere this started happening and only when a new mod is installed (it can be anything from clientside a library or some big mod), and the log always points to numismatic

**Comment by gliscowo** [comment]
According to this crash report, the error is caused by Charm. I don't know if this is a general problem of Charm on 1.19.2 or if it's something in your modpack, but removing it should fix the issue. Numismatic is only caught in the crossfire as this is mixin issue that causes the entire classloading pipeline to collapse, which ultimately makes Numismatic incorrectly seem like the culprit
Cheers

**Comment by masmasmas66** [comment]
The culprit in the end was enchantwithmob
thanks log
