### ISSUE TITLE
Several things that may be cool to implement.

### ISSUE THREAD

**Issue by notIkibo** [glisco03/numismatic-overhaul#54]
First and foremost: Lovely mod, it has so much potential.

1. You should be able to see your purse when interacting with a villager or shop. It's inconvenient to: Get out, look into your inventory and hover over purse and see your balance, get out of your inventory, interact with shop/villager who already ran away. 

2. When exploring or just killing pillagers, you either find purses or silver and bronze coins seperately. 
Two issues with that: 
First, it is going to clog up your inventory. Three spaces - that temporarily (I give you that) - are used for money even though you have a purse and aren't really going to use it in an explorational context where sometimes even one space makes the difference. 
Second, you have to right click them in your hotbar for them to get into your purse. So you have to move stuff everytime you're low on space and get out of your inventory to right click and switch everything back. 
I really hope you see how annoying this can be throughout the whole game. I just found out you can stack the seperate coins into a moneybag and so you have one slot you take, but you still have to put it in a hotbar to right click.
My solution (feel free to ignore this): If you get money out of pillagers or maybe even just collect them from the ground, it gets into your purse directly. In no situation would this cause an inconvenience. (Though I don't know the coding on this one)

You can just put moneybags/coins into the purse icon and it gets added. Maybe so to say, a slot where only four items can be put into (Money bag, gold/silver/bronze coin). 

3. I just tried to setup the infinity shop and I put some items innit, but I couldn't buy anything from it. I guessed that the person who sets up his own shop can't buy his items? But the infinity shop shouldn't be like this. I also don't know what the money counter under the sell trinket is (see in screenshot about point 7). The money you get from buying? What about infi shop "owner": Is he able to collect money from it?

4. I'm assuming for any shops (except infinity shop) to work, the items have to be in the inventory shop. Okay, yes. And it's cool that you can put items innit through hoppers, but what purpose does it serve for the infi shop? And does the infinity shop also need the items in it's inventory? If yes, I still couldn't buy anything from it. And also the one setting up the infi shop has access on the inventory even in survival. That's kinda meh and not bulletproof.

5. I figured this is a newly developed mod (which will be a musthave in the future). But I must say as someone who has read about the mod and decided to give it a try, I was sometimes confused on how it works. How to get coins etc. And that you can stack moneybags in your inventory and all those little tweaks that exists and will exist. Would you see a Patchouli book you can craft with a book and a bronze coin or shop as useful? For newer players who don't know how 7 total items from a mod can change the gameplay in a server so severely, I do see a use for that. 

6. I tried /numismatic balance and it didn't work at all. Oh and what does the networth below actually mean? This value does say something about the value of a single piece of currency, but I haven't played that enough to know how I should setup the infi shop. Maybe also a little instruction on how to balance the infi shop and how to look out for inflation. 
![numismatic balance](https://user-images.githubusercontent.com/106886638/201363327-eb1512f4-89b5-4cf8-a282-3f5aab1b1720.png)

7. When setting up the shop and having Roughly Enough Items (and having cheats activated), you will delete your items when trying to put your item into the sell socket. Small inconvenience and somewhat situational (especially having cheats on) and it does have a fix (either disable cheats or Ctrl+o), but something I stumbled upon when trying to setup the infi shop.
![Delete Item](https://user-images.githubusercontent.com/106886638/201334638-f39466f8-3836-4cdb-b206-4a5278614824.png)

That is everything for now, but again: I have a lot to look forward to in this mod

Sincerely

Ikibo

**Comment by Noaaan** [comment]
Hey, sorry for taking a while to respond. Been a busy few weeks.

Thank you for opening such a detailed issue. I do want to go over all the points you raised regarding Numismatic:

1: This is something we agree with. Adding the Purse Overlay to the Villager Trade Screen when in a Villager Trade screen should be easy enough to do.  

4: I do agree that the Hopper toggle button inside an Inexhaustible Shop is redundant. We might remove that from its interface in the future. 

6: The `numismatic balance` command has another subcommand, which lets you choose how to query the balance of the player/range. This value comes in raw coins (50 = 50 bronze coins, 164 = 1 silver, 64 bronze coins, etc.). This is not something we have documented on the wiki, so thank you for pointing that out!

7: Thanks for noticing, we will see to get that fixed in the next release.  

2, 3, 5: All of these points are in regards to documentation. While Patchouli is a possible solution, we do not believe most players would actually spend their time reading it, and for this mod most of the mechanics should be straight-forward enough that you wouldn't need to. 

We do recieve a lot of questions though, and we have made the effort of documenting most of the mod through our wiki (available over at https://docs.wispforest.io/numismatic-overhaul/home/), and we even have a [video-guide](https://www.youtube.com/watch?v=f2-v_Z_5ZEE) should you wish to view that instead.  

To quickly address your questions; When you have a ton of loose change in your inventory, simply shift clicking your purse icon will instantly deposit all coins from your inventory. It will ignore money bags, so that you can still hold money in your inventory without depositing it on accident. 

If you are an owner of a shop block, if you sneak + use the shop, you will open the trade screen as if you were another player, and you are even able to buy from your own shop. 

Hopefully I managed to answer everything, and thank you for using Numismatic Overhaul.
