### ISSUE TITLE
Crashing when moving in a world.

### ISSUE THREAD

**Issue by TheButterbrotMan** [glisco03/numismatic-overhaul#68]
Hello, my modpack crashes, when im moving. I suspect its connected to MCA.
https://bytebin.lucko.me/GEaQXCk6wY

**Comment by neutralboolean** [comment]
Yup, I noticed it with the new MCA Reborn update today and thought it was an issue on their end. But it's this line:
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method removeDivisor(I)I in numismatic-overhaul.mixins.json:MCAVillageMixin from mod numismatic-overhaul failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap numismatic-overhaul-refmap.json`

**Comment by Noaaan** [comment]
Confirmed. The latest update moved the Tax handling outside of the Village class, so we have to update the compatability. 
We will try get this fixed ASAP

**Comment by TheButterbrotMan** [comment]
> Confirmed. The latest update moved the Tax handling outside of the Village class, so we have to update the compatability. We will try get this fixed ASAP

Are there news on this? 👯

**Comment by Luke100000** [comment]
Taxes can now be customized in the config, `taxesMap`. A mixin inject into `loadOrCreate` maybe? Once fixed I will annotate and protect the affected code from further changes.

**Comment by Noaaan** [comment]
Looking into it and considering you have already provided this config option, I do not really see any reason for us to keep both a Mixin and a config option in our mod. After all, that would complicate and somewhat defeat the purpose of configurability. 
I do want to say thank you for making this change, as it greatly compliments MCA:R!
