### ISSUE TITLE
Cartographer level trade causes crash 0.2.8

### ISSUE THREAD

**Issue by Jameshills** [glisco03/numismatic-overhaul#80]
when trading with a cartographer and they level up from a novice up, you freeze get disconnected and then get a server watchdog crash as your player is still connected but not able to do anything / able to reconnect.  it seems to be when its creating a map trade idk.
for version:
numismatic-overhaul-0.2.8+1.19.jar.

File attached is a log for the crash (may be missing a bit as i had to copy it from the terminal rather than the file)
[crashlog.txt](https://github.com/wisp-forest/numismatic-overhaul/files/10961717/crashlog.txt)

**Comment by Noaaan** [comment]
This issue is related to vanilla, and happens due to the server lagging out while the cartographer is searching for a specific structure. It is not something we can exactly fix within Numismatic Overhaul.

I do recommend a mod like Structure Essentials, as it heavily improves this search algorithm, possibly preventing your server from lagging out.
https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric

Alternatively, in your servers `server.properties` file (server config), you can increase the `max-tick-time` to something higher. I believe 120000 ticks (2 minutes) is usually required for slow servers + heavy modpacks.
