### ISSUE TITLE
1.19.4 Crashes with You're in Grave Danger

### ISSUE THREAD

**Issue by B1n-ry** [glisco03/numismatic-overhaul#83]
I'm the developer of the grave mod "You're in Grave Danger" (yigd short), and I got reported to me the other day of an incompatibility with numismatic overhaul in 1.19.4. I've recently released an update of yigd where my graves will be able to store coins from your mod, but I guess soomehow this one slipped past my testing. Anyhow after looking at the crash, I'm pretty sure that there's no obvious flaw in my approach to moving coins from and to the player. You can check out my implementation [here](https://github.com/B1n-ry/Youre-in-grave-danger/blob/1.19.4/src/main/java/com/b1n_ry/yigd/compat/NumismaticOverhaulCompat.java).

When dying with any coins in the purse thingy, everything first works as normal, but when you respawn, the game crash. What happens is that my mod deletes all items from the player on death, and restores the items that shouldn't be lost on respawn (like soulbound enchantments, and in this instance, some of the leftover coins). When modifying the currency component on respawn, that's when the game crashes. I've been able to reproduce this in a singleplayer world if that makes any difference.
Here's the [crash-log](https://github.com/wisp-forest/numismatic-overhaul/files/11342062/crash-2023-04-26_18.55.37-server.txt)

I'm not sure if this digs more into owo-lib or if the issue lies in numismatic overhaul itself, but it after all only happens with this mod in perticular (together with yigd of course), and it's the same dev for both mods, so that's why I'm putting the issue here.
If it however would be something I'm doing wrong or should be doing differently, please let me know so I can fix this on my end. Let me know if you have any questions about my implementation of the compatibility between the mods on my side, as I'd be happy to help

**Comment by gliscowo** [comment]
Your implementation looks perfectly correct to me, and in fact we have discovered this problem ourselves a few days while running a playtesting server for a different mod we're developing. 

In the end it boils down to an issue in owo-lib's implementation of server-sided access to a client's config values (which Numismatic uses to decide where to display the message that your balance changed). I've already implemented a fix in owo-lib dev builds - however, since it's currently halfway through another major version, I haven't yet found the time to isolate the patch and release a fixed build of the currently public major release.

I'll see about releasing it when I get the time, but for the time being I think sadly the only mitigation is to use either a version of yigd that does not yet have Numismatic compat, or the previous release of Numismatic which does not bring this config option

Cheers

**Comment by notIkibo** [comment]
Wonderful news!

If in the future the numismatic compat is available on 1.19.4, will it be available for 1.19 as a whole too?
Both mods are extremely necessary, if you're thinking to make mc better. 
If it's a no, completely fine. I'm in no right to demand anything. Just a question

I'm happy that devs get along though :3

**Comment by B1n-ry** [comment]
In reply to @notIkibo:
As far as I'm aware the 1.19 compat works. At least there should be an implementation for it. I'm also pretty sure I remember testing 1.19 and 1.19.3 compat once this issue was reported to me without finding any issue, so it should work.
The numismatic overhaul compat is implemented in versions 1.18.2 - 1.19.4, but only the 1.19.4 versions compat seems to cause this crash

**Comment by gliscowo** [comment]
Today I bring good news!

Along with a wave of other fixes I've now released a [stable build for 1.19.4](https://modrinth.com/mod/owo-lib/version/0.10.6+1.19.4) which contains the fix for this from the prereleases

As such, I'll be closing this issue
Cheers
