### ISSUE TITLE
Infinite money duplication glitch [1.19.4]

### ISSUE THREAD

**Issue by NantaArthur123** [glisco03/numismatic-overhaul#85]
Game version: 1.19.4
Fabric version: 0.14.19

How to recreate:
*I'm not too sure how to recreate it but maybe it's like this*
1. Install Open parties and claim
2. set claim
3. other player who don't have the permissions to claim tries to put the shop in the claim
4. the shop disappear from hand
5. go out from the claim region
6. swap the shop with coin (gold/bronze/silver)
7. right click the items and keep swaping

Video of the bug/glitch
https://www.youtube.com/live/iv0-rCBN5OE?feature=share&t=2520
at time 42:00

**Comment by JackoDEJ** [comment]
Ping

**Comment by gliscowo** [comment]
There are two problems with this issue
1. I haven't been able to reproduce it in my testing, although that may be because I didn't quite understand the instructions (what does swapping mean exactly?)
2. There are only two possible outcomes - either this issue is purely client-sided (and thereby purely cosmetic) or it's a fundamental problem of how OPAC handles item usage in claims, which is not something that Numismatic should be responsible for or even can fix

If you could try giving us a better description, ideally with a video and a minimal modlist, for reproducing this, we can try taking another look at it - but for now we'll treat this is as an external issue that you should probably report on OPAC separately

Cheers

**Comment by Noaaan** [comment]
We are not sure whether this still is an issue. If you can reproduce this in a controlled context feel free to re-open this. Otherwise, it will stay closed for now. If you do find another bug or glitch please open a new issue
